"""initial schema

Revision ID: 62dd5ee0f369
Revises: 
Create Date: 2026-06-25 00:15:31.007399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '62dd5ee0f369'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
